// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WKFTournamentIS.DataAccess.Data;

#nullable disable

namespace WKFTournamentIS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250529121351_AddTournamentTable")]
    partial class AddTournamentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WKFTournamentIS.Core.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BeginningDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndingDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeginningDateTime = new DateTime(2025, 6, 28, 14, 13, 51, 48, DateTimeKind.Local).AddTicks(7251),
                            EndingDateTime = new DateTime(2025, 6, 30, 14, 13, 51, 48, DateTimeKind.Local).AddTicks(7342),
                            Location = "Sportska hala Partizan, Beograd",
                            Name = "Nacionalno prvenstvo u karateu"
                        },
                        new
                        {
                            Id = 2,
                            BeginningDateTime = new DateTime(2025, 5, 14, 14, 13, 51, 48, DateTimeKind.Local).AddTicks(7354),
                            EndingDateTime = new DateTime(2025, 5, 16, 14, 13, 51, 48, DateTimeKind.Local).AddTicks(7357),
                            Location = "Sportski centar Borik, Banja Luka",
                            Name = "Međunarodni turnir Banja Luka Open"
                        });
                });

            modelBuilder.Entity("WKFTournamentIS.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$zWHS9TKs02cHcunGsfMEA.IMMtgy.qKQN8DPSxTuyu9Ylu/0Vz1Sy",
                            Role = 0,
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
