//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WKFTournamentIS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WKFTournamentIS.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑️ Obriši.
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👁️ Detalji.
        /// </summary>
        public static string Action_Details {
            get {
                return ResourceManager.GetString("Action_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✏️ Izmjeni.
        /// </summary>
        public static string Action_Edit {
            get {
                return ResourceManager.GetString("Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✏️ Izmjeni šifru.
        /// </summary>
        public static string Action_EditPassword {
            get {
                return ResourceManager.GetString("Action_EditPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✏️ Ažuriraj plasman.
        /// </summary>
        public static string Action_UpdatePlacement {
            get {
                return ResourceManager.GetString("Action_UpdatePlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Dodaj kategoriju.
        /// </summary>
        public static string Add_Category {
            get {
                return ResourceManager.GetString("Add_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Dodaj klub.
        /// </summary>
        public static string Add_Club {
            get {
                return ResourceManager.GetString("Add_Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Dodaj takmičara.
        /// </summary>
        public static string Add_Competitor {
            get {
                return ResourceManager.GetString("Add_Competitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Dodaj operatora.
        /// </summary>
        public static string Add_Operator {
            get {
                return ResourceManager.GetString("Add_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Dodaj takmičenje.
        /// </summary>
        public static string Add_Tournament {
            get {
                return ResourceManager.GetString("Add_Tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o kategoriji.
        /// </summary>
        public static string AddEditCategory_Header {
            get {
                return ResourceManager.GetString("AddEditCategory_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje označeno sa .
        /// </summary>
        public static string AddEditCategory_Info_FieldMarkedWith {
            get {
                return ResourceManager.GetString("AddEditCategory_Info_FieldMarkedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  je obavezno..
        /// </summary>
        public static string AddEditCategory_Info_IsRequired {
            get {
                return ResourceManager.GetString("AddEditCategory_Info_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv kategorije *.
        /// </summary>
        public static string AddEditCategory_LblCategoryName {
            get {
                return ResourceManager.GetString("AddEditCategory_LblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novu kategoriju.
        /// </summary>
        public static string AddEditCategory_Title_Add {
            get {
                return ResourceManager.GetString("AddEditCategory_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni kategoriju.
        /// </summary>
        public static string AddEditCategory_Title_Edit {
            get {
                return ResourceManager.GetString("AddEditCategory_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija.
        /// </summary>
        public static string AddEditCategory_TitleBarText {
            get {
                return ResourceManager.GetString("AddEditCategory_TitleBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv kluba *.
        /// </summary>
        public static string AddEditClub_LblClubName {
            get {
                return ResourceManager.GetString("AddEditClub_LblClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novi klub.
        /// </summary>
        public static string AddEditClub_Title_Add {
            get {
                return ResourceManager.GetString("AddEditClub_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjeni klub.
        /// </summary>
        public static string AddEditClub_Title_Edit {
            get {
                return ResourceManager.GetString("AddEditClub_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o takmičaru.
        /// </summary>
        public static string AddEditCompetitor_Header {
            get {
                return ResourceManager.GetString("AddEditCompetitor_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sva polja označena sa .
        /// </summary>
        public static string AddEditCompetitor_Info_AllFieldsRequired {
            get {
                return ResourceManager.GetString("AddEditCompetitor_Info_AllFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klub *.
        /// </summary>
        public static string AddEditCompetitor_LblClub {
            get {
                return ResourceManager.GetString("AddEditCompetitor_LblClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja *.
        /// </summary>
        public static string AddEditCompetitor_LblDateOfBirth {
            get {
                return ResourceManager.GetString("AddEditCompetitor_LblDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime *.
        /// </summary>
        public static string AddEditCompetitor_LblFirstName {
            get {
                return ResourceManager.GetString("AddEditCompetitor_LblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime *.
        /// </summary>
        public static string AddEditCompetitor_LblLastName {
            get {
                return ResourceManager.GetString("AddEditCompetitor_LblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novog takmičara.
        /// </summary>
        public static string AddEditCompetitor_Title_Add {
            get {
                return ResourceManager.GetString("AddEditCompetitor_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjeni takmičara: {0} {1}.
        /// </summary>
        public static string AddEditCompetitor_Title_Edit {
            get {
                return ResourceManager.GetString("AddEditCompetitor_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takmičar.
        /// </summary>
        public static string AddEditCompetitor_TitleBarText {
            get {
                return ResourceManager.GetString("AddEditCompetitor_TitleBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o operatoru.
        /// </summary>
        public static string AddEditOperator_Header {
            get {
                return ResourceManager.GetString("AddEditOperator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora imati najmanje 6 karaktera..
        /// </summary>
        public static string AddEditOperator_Info_PasswordMinLength {
            get {
                return ResourceManager.GetString("AddEditOperator_Info_PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi lozinku *.
        /// </summary>
        public static string AddEditOperator_LblConfirmPassword {
            get {
                return ResourceManager.GetString("AddEditOperator_LblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka *.
        /// </summary>
        public static string AddEditOperator_LblPassword {
            get {
                return ResourceManager.GetString("AddEditOperator_LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime *.
        /// </summary>
        public static string AddEditOperator_LblUsername {
            get {
                return ResourceManager.GetString("AddEditOperator_LblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novog operatora.
        /// </summary>
        public static string AddEditOperator_Title_Add {
            get {
                return ResourceManager.GetString("AddEditOperator_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjeni operatora: {0}.
        /// </summary>
        public static string AddEditOperator_Title_Edit {
            get {
                return ResourceManager.GetString("AddEditOperator_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string AddEditOperator_TitleBarText {
            get {
                return ResourceManager.GetString("AddEditOperator_TitleBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o takmičenju.
        /// </summary>
        public static string AddTournament_Header {
            get {
                return ResourceManager.GetString("AddTournament_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme unesite u 24-časovnom formatu (00-23 za sate, 00-59 za minute)..
        /// </summary>
        public static string AddTournament_Info_TimeFormat {
            get {
                return ResourceManager.GetString("AddTournament_Info_TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum i vreme početka *.
        /// </summary>
        public static string AddTournament_LblBeginningDateTime {
            get {
                return ResourceManager.GetString("AddTournament_LblBeginningDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum i vreme završetka *.
        /// </summary>
        public static string AddTournament_LblEndingDateTime {
            get {
                return ResourceManager.GetString("AddTournament_LblEndingDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija *.
        /// </summary>
        public static string AddTournament_LblLocation {
            get {
                return ResourceManager.GetString("AddTournament_LblLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raspored takmičenja.
        /// </summary>
        public static string AddTournament_LblSchedule {
            get {
                return ResourceManager.GetString("AddTournament_LblSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv takmičenja *.
        /// </summary>
        public static string AddTournament_LblTournamentName {
            get {
                return ResourceManager.GetString("AddTournament_LblTournamentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novo takmičenje.
        /// </summary>
        public static string AddTournament_Title_Add {
            get {
                return ResourceManager.GetString("AddTournament_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjeni takmičenje.
        /// </summary>
        public static string AddTournament_Title_Edit {
            get {
                return ResourceManager.GetString("AddTournament_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takmičenje.
        /// </summary>
        public static string AddTournament_TitleBarText {
            get {
                return ResourceManager.GetString("AddTournament_TitleBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Panel.
        /// </summary>
        public static string AdminWindowTitle {
            get {
                return ResourceManager.GetString("AdminWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi kategoriju *.
        /// </summary>
        public static string AssignCategory_LblSelectCategory {
            get {
                return ResourceManager.GetString("AssignCategory_LblSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema više dostupnih kategorija za dodavanje..
        /// </summary>
        public static string AssignCategory_NoAvailableCategories {
            get {
                return ResourceManager.GetString("AssignCategory_NoAvailableCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj kategoriju na turnir.
        /// </summary>
        public static string AssignCategory_TitleBarText {
            get {
                return ResourceManager.GetString("AssignCategory_TitleBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodeli kategoriju.
        /// </summary>
        public static string AssignCategory_WindowTitle {
            get {
                return ResourceManager.GetString("AssignCategory_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIJAVI SE.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkaži.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Dodaj takmičara.
        /// </summary>
        public static string CategoryCompetitors_BtnAddCompetitor {
            get {
                return ResourceManager.GetString("CategoryCompetitors_BtnAddCompetitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑️ Ukloni takmičara.
        /// </summary>
        public static string CategoryCompetitors_BtnRemoveCompetitor {
            get {
                return ResourceManager.GetString("CategoryCompetitors_BtnRemoveCompetitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takmičari za kategoriju: &apos;{0}&apos; na turniru: &apos;{1}&apos;.
        /// </summary>
        public static string CategoryCompetitors_PageSubtitle {
            get {
                return ResourceManager.GetString("CategoryCompetitors_PageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takmičari - {0}.
        /// </summary>
        public static string CategoryCompetitors_WindowTitle {
            get {
                return ResourceManager.GetString("CategoryCompetitors_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda zatvaranja.
        /// </summary>
        public static string Confirm_CloseApp_Caption {
            get {
                return ResourceManager.GetString("Confirm_CloseApp_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da zatvorite aplikaciju?.
        /// </summary>
        public static string Confirm_CloseApp_Text {
            get {
                return ResourceManager.GetString("Confirm_CloseApp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda brisanja.
        /// </summary>
        public static string Confirm_Delete_Caption {
            get {
                return ResourceManager.GetString("Confirm_Delete_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da obrišete kategoriju &apos;{0}&apos;?.
        /// </summary>
        public static string Confirm_DeleteCategory_Text {
            get {
                return ResourceManager.GetString("Confirm_DeleteCategory_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da obrišete klub &apos;{0}&apos;?.
        /// </summary>
        public static string Confirm_DeleteClub_Text {
            get {
                return ResourceManager.GetString("Confirm_DeleteClub_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da obrišete takmičara &apos;{0} {1}&apos;?.
        /// </summary>
        public static string Confirm_DeleteCompetitor_Text {
            get {
                return ResourceManager.GetString("Confirm_DeleteCompetitor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da obrišete operatora &apos;{0}&apos;?.
        /// </summary>
        public static string Confirm_DeleteOperator_Text {
            get {
                return ResourceManager.GetString("Confirm_DeleteOperator_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da obrišete takmičenje &apos;{0}&apos;?.
        /// </summary>
        public static string Confirm_DeleteTournament_Text {
            get {
                return ResourceManager.GetString("Confirm_DeleteTournament_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda odjave.
        /// </summary>
        public static string Confirm_Logout_Caption {
            get {
                return ResourceManager.GetString("Confirm_Logout_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da se želite odjaviti?.
        /// </summary>
        public static string Confirm_Logout_Text {
            get {
                return ResourceManager.GetString("Confirm_Logout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da uklonite kategoriju &apos;{0}&apos; sa ovog turnira?.
        /// </summary>
        public static string Confirm_RemoveCategoryFromTournament_Text {
            get {
                return ResourceManager.GetString("Confirm_RemoveCategoryFromTournament_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da uklonite takmičara &apos;{0}&apos; iz ove kategorije?.
        /// </summary>
        public static string Confirm_RemoveCompetitor_Text {
            get {
                return ResourceManager.GetString("Confirm_RemoveCompetitor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © WKF Tournament Management System.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri dodavanju kategorije: {0}.
        /// </summary>
        public static string Error_AddingCategoryToTournament {
            get {
                return ResourceManager.GetString("Error_AddingCategoryToTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće pronaći vezu kategorije i turnira..
        /// </summary>
        public static string Error_CategoryTournamentLinkNotFound {
            get {
                return ResourceManager.GetString("Error_CategoryTournamentLinkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proverite da li klub ima povezane takmičare..
        /// </summary>
        public static string Error_ClubConnected {
            get {
                return ResourceManager.GetString("Error_ClubConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moguće je da je takmičar povezan sa drugim podacima (npr. rezultatima) i ne može biti obrisan..
        /// </summary>
        public static string Error_CompetitorConnected {
            get {
                return ResourceManager.GetString("Error_CompetitorConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o takmičaru nisu dostupni..
        /// </summary>
        public static string Error_CompetitorDataMissing {
            get {
                return ResourceManager.GetString("Error_CompetitorDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška u bazi.
        /// </summary>
        public static string Error_Database {
            get {
                return ResourceManager.GetString("Error_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brisanje nije uspelo..
        /// </summary>
        public static string Error_Deleting {
            get {
                return ResourceManager.GetString("Error_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        public static string Error_Generic {
            get {
                return ResourceManager.GetString("Error_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju dostupnih kategorija: {0}.
        /// </summary>
        public static string Error_LoadingAvailableCategories {
            get {
                return ResourceManager.GetString("Error_LoadingAvailableCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju dostupnih takmičara: {0}.
        /// </summary>
        public static string Error_LoadingAvailableCompetitors {
            get {
                return ResourceManager.GetString("Error_LoadingAvailableCompetitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom učitavanja kategorija..
        /// </summary>
        public static string Error_LoadingCategories {
            get {
                return ResourceManager.GetString("Error_LoadingCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju kategorija: {0}.
        /// </summary>
        public static string Error_LoadingCategoriesForTournament {
            get {
                return ResourceManager.GetString("Error_LoadingCategoriesForTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom učitavanja klubova..
        /// </summary>
        public static string Error_LoadingClubs {
            get {
                return ResourceManager.GetString("Error_LoadingClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju klubova: {0}.
        /// </summary>
        public static string Error_LoadingClubs_MessageBox {
            get {
                return ResourceManager.GetString("Error_LoadingClubs_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom učitavanja takmičara..
        /// </summary>
        public static string Error_LoadingCompetitors {
            get {
                return ResourceManager.GetString("Error_LoadingCompetitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom učitavanja operatora..
        /// </summary>
        public static string Error_LoadingOperators {
            get {
                return ResourceManager.GetString("Error_LoadingOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju takmičara: {0}.
        /// </summary>
        public static string Error_LoadingRegisteredCompetitors {
            get {
                return ResourceManager.GetString("Error_LoadingRegisteredCompetitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom učitavanja takmičenja..
        /// </summary>
        public static string Error_LoadingTournaments {
            get {
                return ResourceManager.GetString("Error_LoadingTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri registraciji takmičara: {0}.
        /// </summary>
        public static string Error_RegisteringCompetitor {
            get {
                return ResourceManager.GetString("Error_RegisteringCompetitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uklanjanje kategorije nije uspelo..
        /// </summary>
        public static string Error_RemovingCategoryFromTournament_Failed {
            get {
                return ResourceManager.GetString("Error_RemovingCategoryFromTournament_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri uklanjanju kategorije: {0}.
        /// </summary>
        public static string Error_RemovingCategoryFromTournament_Generic {
            get {
                return ResourceManager.GetString("Error_RemovingCategoryFromTournament_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uklanjanje takmičara nije uspelo..
        /// </summary>
        public static string Error_RemovingCompetitor_Failed {
            get {
                return ResourceManager.GetString("Error_RemovingCompetitor_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri uklanjanju takmičara: {0}.
        /// </summary>
        public static string Error_RemovingCompetitor_Generic {
            get {
                return ResourceManager.GetString("Error_RemovingCompetitor_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri čuvanju.
        /// </summary>
        public static string Error_Saving {
            get {
                return ResourceManager.GetString("Error_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije uspelo dodavanje takmičenja u bazu..
        /// </summary>
        public static string Error_SavingTournament {
            get {
                return ResourceManager.GetString("Error_SavingTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriranje plasmana nije uspelo: {0}.
        /// </summary>
        public static string Error_UpdatePlacementFailed {
            get {
                return ResourceManager.GetString("Error_UpdatePlacementFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriranje nije uspelo..
        /// </summary>
        public static string Error_Updating {
            get {
                return ResourceManager.GetString("Error_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije uspelo ažuriranje takmičenja..
        /// </summary>
        public static string Error_UpdatingTournament {
            get {
                return ResourceManager.GetString("Error_UpdatingTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška validacije.
        /// </summary>
        public static string Error_Validation {
            get {
                return ResourceManager.GetString("Error_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan unos.
        /// </summary>
        public static string Error_Validation_Caption {
            get {
                return ResourceManager.GetString("Error_Validation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema kluba.
        /// </summary>
        public static string Fallback_NoClub {
            get {
                return ResourceManager.GetString("Fallback_NoClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv kategorije.
        /// </summary>
        public static string GridHeader_CategoryName {
            get {
                return ResourceManager.GetString("GridHeader_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klub.
        /// </summary>
        public static string GridHeader_Club {
            get {
                return ResourceManager.GetString("GridHeader_Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv kluba.
        /// </summary>
        public static string GridHeader_ClubName {
            get {
                return ResourceManager.GetString("GridHeader_ClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja.
        /// </summary>
        public static string GridHeader_DateOfBirth {
            get {
                return ResourceManager.GetString("GridHeader_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum završetka.
        /// </summary>
        public static string GridHeader_EndDate {
            get {
                return ResourceManager.GetString("GridHeader_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string GridHeader_FirstName {
            get {
                return ResourceManager.GetString("GridHeader_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string GridHeader_LastName {
            get {
                return ResourceManager.GetString("GridHeader_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija.
        /// </summary>
        public static string GridHeader_Location {
            get {
                return ResourceManager.GetString("GridHeader_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plasman.
        /// </summary>
        public static string GridHeader_Placement {
            get {
                return ResourceManager.GetString("GridHeader_Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum početka.
        /// </summary>
        public static string GridHeader_StartDate {
            get {
                return ResourceManager.GetString("GridHeader_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv takmičenja.
        /// </summary>
        public static string GridHeader_TournamentName {
            get {
                return ResourceManager.GetString("GridHeader_TournamentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string GridHeader_Username {
            get {
                return ResourceManager.GetString("GridHeader_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravno korisničko ime ili lozinka..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klub.
        /// </summary>
        public static string Label_Club {
            get {
                return ResourceManager.GetString("Label_Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takmičar.
        /// </summary>
        public static string Label_Competitor {
            get {
                return ResourceManager.GetString("Label_Competitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutni plasman.
        /// </summary>
        public static string Label_CurrentPlacement {
            get {
                return ResourceManager.GetString("Label_CurrentPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi plasman.
        /// </summary>
        public static string Label_NewPlacement {
            get {
                return ResourceManager.GetString("Label_NewPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string LblUsername {
            get {
                return ResourceManager.GetString("LblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške prilikom prijave. Molimo pokušajte ponovo..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriranje plasmana nije uspelo: {0}.
        /// </summary>
        public static string MessageBox_UpdatePlacementErrorText {
            get {
                return ResourceManager.GetString("MessageBox_UpdatePlacementErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        public static string MessageBox_UpdatePlacementErrorTitle {
            get {
                return ResourceManager.GetString("MessageBox_UpdatePlacementErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plasman takmičara je uspešno ažuriran..
        /// </summary>
        public static string MessageBox_UpdatePlacementSuccessText {
            get {
                return ResourceManager.GetString("MessageBox_UpdatePlacementSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspeh.
        /// </summary>
        public static string MessageBox_UpdatePlacementSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBox_UpdatePlacementSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo unesite lozinku..
        /// </summary>
        public static string MsgEmptyPassword {
            get {
                return ResourceManager.GetString("MsgEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo unesite korisničko ime..
        /// </summary>
        public static string MsgEmptyUsername {
            get {
                return ResourceManager.GetString("MsgEmptyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📋 Kategorije.
        /// </summary>
        public static string NavButton_Categories {
            get {
                return ResourceManager.GetString("NavButton_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏢 Klubovi.
        /// </summary>
        public static string NavButton_Clubs {
            get {
                return ResourceManager.GetString("NavButton_Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥋 Takmičari.
        /// </summary>
        public static string NavButton_Competitors {
            get {
                return ResourceManager.GetString("NavButton_Competitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚪 Odjavi se.
        /// </summary>
        public static string NavButton_Logout {
            get {
                return ResourceManager.GetString("NavButton_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👤 Operatori.
        /// </summary>
        public static string NavButton_Operators {
            get {
                return ResourceManager.GetString("NavButton_Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙️ Podešavanja.
        /// </summary>
        public static string NavButton_Settings {
            get {
                return ResourceManager.GetString("NavButton_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏆 Takmičenja.
        /// </summary>
        public static string NavButton_Tournaments {
            get {
                return ResourceManager.GetString("NavButton_Tournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPRAVLJANJE.
        /// </summary>
        public static string NavGroup_Management {
            get {
                return ResourceManager.GetString("NavGroup_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SISTEM.
        /// </summary>
        public static string NavGroup_System {
            get {
                return ResourceManager.GetString("NavGroup_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Panel.
        /// </summary>
        public static string OperatorWindowTitle {
            get {
                return ResourceManager.GetString("OperatorWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizujte kategorije po takmičenjima.
        /// </summary>
        public static string PageSubtitle_Categories {
            get {
                return ResourceManager.GetString("PageSubtitle_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajte, mijenjajte i upravljajte klubovima.
        /// </summary>
        public static string PageSubtitle_Clubs {
            get {
                return ResourceManager.GetString("PageSubtitle_Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljajte takmičarima i njihovim registracijama.
        /// </summary>
        public static string PageSubtitle_Competitors {
            get {
                return ResourceManager.GetString("PageSubtitle_Competitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajte, mijenjajte i upravljajte operatorskim nalozima.
        /// </summary>
        public static string PageSubtitle_Operators {
            get {
                return ResourceManager.GetString("PageSubtitle_Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavajte, mijenjajte i upravljajte takmičenjima.
        /// </summary>
        public static string PageSubtitle_Tournaments {
            get {
                return ResourceManager.GetString("PageSubtitle_Tournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled postojećih takmičenja.
        /// </summary>
        public static string PageSubtitle_Tournaments_Operator {
            get {
                return ResourceManager.GetString("PageSubtitle_Tournaments_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljanje kategorijama.
        /// </summary>
        public static string PageTitle_Categories {
            get {
                return ResourceManager.GetString("PageTitle_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljanje klubovima.
        /// </summary>
        public static string PageTitle_Clubs {
            get {
                return ResourceManager.GetString("PageTitle_Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljanje takmičarima.
        /// </summary>
        public static string PageTitle_Competitors {
            get {
                return ResourceManager.GetString("PageTitle_Competitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljanje operatorima.
        /// </summary>
        public static string PageTitle_Operators {
            get {
                return ResourceManager.GetString("PageTitle_Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljanje takmičenjima.
        /// </summary>
        public static string PageTitle_Tournaments {
            get {
                return ResourceManager.GetString("PageTitle_Tournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka za operatora &apos;{0}&apos; je uspešno promenjena..
        /// </summary>
        public static string PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije postavljen.
        /// </summary>
        public static string Placement_NotSet {
            get {
                return ResourceManager.GetString("Placement_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi takmičara *.
        /// </summary>
        public static string RegisterCompetitor_LblSelectCompetitor {
            get {
                return ResourceManager.GetString("RegisterCompetitor_LblSelectCompetitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema više dostupnih takmičara za registraciju..
        /// </summary>
        public static string RegisterCompetitor_NoAvailableCompetitors {
            get {
                return ResourceManager.GetString("RegisterCompetitor_NoAvailableCompetitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registruj takmičara za kategoriju.
        /// </summary>
        public static string RegisterCompetitor_TitleBarText {
            get {
                return ResourceManager.GetString("RegisterCompetitor_TitleBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registruj takmičara.
        /// </summary>
        public static string RegisterCompetitor_WindowTitle {
            get {
                return ResourceManager.GetString("RegisterCompetitor_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretražite kategorije....
        /// </summary>
        public static string Search_Categories {
            get {
                return ResourceManager.GetString("Search_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretražite klubove....
        /// </summary>
        public static string Search_Clubs {
            get {
                return ResourceManager.GetString("Search_Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretražite takmičare....
        /// </summary>
        public static string Search_Competitors {
            get {
                return ResourceManager.GetString("Search_Competitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretražite operatore....
        /// </summary>
        public static string Search_Operators {
            get {
                return ResourceManager.GetString("Search_Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretražite....
        /// </summary>
        public static string Search_Tooltip {
            get {
                return ResourceManager.GetString("Search_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretražite takmičenja....
        /// </summary>
        public static string Search_Tournaments {
            get {
                return ResourceManager.GetString("Search_Tournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretražite....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacija.
        /// </summary>
        public static string Settings_Info_Caption {
            get {
                return ResourceManager.GetString("Settings_Info_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja - funkcionalnost u razvoju.
        /// </summary>
        public static string Settings_Info_Text {
            get {
                return ResourceManager.GetString("Settings_Info_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podesite vizuelni izgled aplikacije.
        /// </summary>
        public static string Settings_PageSubtitle {
            get {
                return ResourceManager.GetString("Settings_PageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja Teme.
        /// </summary>
        public static string Settings_Theme_Header {
            get {
                return ResourceManager.GetString("Settings_Theme_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite temu aplikacije:.
        /// </summary>
        public static string Settings_Theme_SelectLabel {
            get {
                return ResourceManager.GetString("Settings_Theme_SelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešno dodato..
        /// </summary>
        public static string Status_Added {
            get {
                return ResourceManager.GetString("Status_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje....
        /// </summary>
        public static string Status_Adding {
            get {
                return ResourceManager.GetString("Status_Adding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešno obrisano..
        /// </summary>
        public static string Status_Deleted {
            get {
                return ResourceManager.GetString("Status_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brisanje....
        /// </summary>
        public static string Status_Deleting {
            get {
                return ResourceManager.GetString("Status_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitavanje podataka....
        /// </summary>
        public static string Status_Loading {
            get {
                return ResourceManager.GetString("Status_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitavanje kategorija....
        /// </summary>
        public static string Status_LoadingCategories {
            get {
                return ResourceManager.GetString("Status_LoadingCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitavanje klubova....
        /// </summary>
        public static string Status_LoadingClubs {
            get {
                return ResourceManager.GetString("Status_LoadingClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitavanje takmičara....
        /// </summary>
        public static string Status_LoadingCompetitors {
            get {
                return ResourceManager.GetString("Status_LoadingCompetitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitavanje operatora....
        /// </summary>
        public static string Status_LoadingOperators {
            get {
                return ResourceManager.GetString("Status_LoadingOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitavanje takmičenja....
        /// </summary>
        public static string Status_LoadingTournaments {
            get {
                return ResourceManager.GetString("Status_LoadingTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremno.
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazuje se {0} kategorija..
        /// </summary>
        public static string Status_ShowingCategories {
            get {
                return ResourceManager.GetString("Status_ShowingCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazuje se {0} klubova..
        /// </summary>
        public static string Status_ShowingClubs {
            get {
                return ResourceManager.GetString("Status_ShowingClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazuje se {0} takmičara..
        /// </summary>
        public static string Status_ShowingCompetitors {
            get {
                return ResourceManager.GetString("Status_ShowingCompetitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazuje se {0} operatora..
        /// </summary>
        public static string Status_ShowingOperators {
            get {
                return ResourceManager.GetString("Status_ShowingOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazuje se {0} takmičenja..
        /// </summary>
        public static string Status_ShowingTournaments {
            get {
                return ResourceManager.GetString("Status_ShowingTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupno:.
        /// </summary>
        public static string Status_Total {
            get {
                return ResourceManager.GetString("Status_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešno ažurirano..
        /// </summary>
        public static string Status_Updated {
            get {
                return ResourceManager.GetString("Status_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriranje....
        /// </summary>
        public static string Status_Updating {
            get {
                return ResourceManager.GetString("Status_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspeh.
        /// </summary>
        public static string Success_Caption {
            get {
                return ResourceManager.GetString("Success_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspeh.
        /// </summary>
        public static string Success_Generic_Caption {
            get {
                return ResourceManager.GetString("Success_Generic_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WKF Tournament System - Prijava.
        /// </summary>
        public static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        public static string Tooltip_Close {
            get {
                return ResourceManager.GetString("Tooltip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimizuj.
        /// </summary>
        public static string Tooltip_Maximize {
            get {
                return ResourceManager.GetString("Tooltip_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimizuj.
        /// </summary>
        public static string Tooltip_Minimize {
            get {
                return ResourceManager.GetString("Tooltip_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite pozitivan ceo broj za plasman. Ostavite polje prazno ukoliko želite da uklonite postojeći plasman..
        /// </summary>
        public static string Tooltip_PlacementInputInfo {
            get {
                return ResourceManager.GetString("Tooltip_PlacementInputInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrati.
        /// </summary>
        public static string Tooltip_Restore {
            get {
                return ResourceManager.GetString("Tooltip_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Dodaj kategoriju.
        /// </summary>
        public static string TournamentCategories_BtnAddCategory {
            get {
                return ResourceManager.GetString("TournamentCategories_BtnAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑️ Ukloni kategoriju.
        /// </summary>
        public static string TournamentCategories_BtnRemoveCategory {
            get {
                return ResourceManager.GetString("TournamentCategories_BtnRemoveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👥 Takmičari.
        /// </summary>
        public static string TournamentCategories_BtnViewCompetitors {
            get {
                return ResourceManager.GetString("TournamentCategories_BtnViewCompetitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled i upravljanje kategorijama za turnir: {0}.
        /// </summary>
        public static string TournamentCategories_PageSubtitle {
            get {
                return ResourceManager.GetString("TournamentCategories_PageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled kategorija za turnir: {0}.
        /// </summary>
        public static string TournamentCategories_PageSubtitle_Operator {
            get {
                return ResourceManager.GetString("TournamentCategories_PageSubtitle_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorije za: {0}.
        /// </summary>
        public static string TournamentCategories_WindowTitle {
            get {
                return ResourceManager.GetString("TournamentCategories_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepoznata ili nepodržana korisnička uloga..
        /// </summary>
        public static string UnknownRole {
            get {
                return ResourceManager.GetString("UnknownRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o plasmanu takmičara.
        /// </summary>
        public static string UpdatePlacement_Header {
            get {
                return ResourceManager.GetString("UpdatePlacement_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriranje plasmana.
        /// </summary>
        public static string UpdatePlacement_WindowTitle {
            get {
                return ResourceManager.GetString("UpdatePlacement_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj plasman za takmičara.
        /// </summary>
        public static string UpdatePlacementWindow_Header {
            get {
                return ResourceManager.GetString("UpdatePlacementWindow_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite plasman takmičara (npr. 1, 2, 3)..
        /// </summary>
        public static string UpdatePlacementWindow_InfoPlacementDetails {
            get {
                return ResourceManager.GetString("UpdatePlacementWindow_InfoPlacementDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klub:.
        /// </summary>
        public static string UpdatePlacementWindow_LblCompetitorClub {
            get {
                return ResourceManager.GetString("UpdatePlacementWindow_LblCompetitorClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o takmičaru.
        /// </summary>
        public static string UpdatePlacementWindow_LblCompetitorInfo {
            get {
                return ResourceManager.GetString("UpdatePlacementWindow_LblCompetitorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime i prezime:.
        /// </summary>
        public static string UpdatePlacementWindow_LblCompetitorName {
            get {
                return ResourceManager.GetString("UpdatePlacementWindow_LblCompetitorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plasman:.
        /// </summary>
        public static string UpdatePlacementWindow_LblPlacement {
            get {
                return ResourceManager.GetString("UpdatePlacementWindow_LblPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriranje plasmana takmičara.
        /// </summary>
        public static string UpdatePlacementWindow_TitleBarText {
            get {
                return ResourceManager.GetString("UpdatePlacementWindow_TitleBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum početka ne može biti u prošlosti..
        /// </summary>
        public static string Validation_BeginningDateInPast {
            get {
                return ResourceManager.GetString("Validation_BeginningDateInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv može imati maksimalno 500 karaktera..
        /// </summary>
        public static string Validation_CategoryNameMaxLength {
            get {
                return ResourceManager.GetString("Validation_CategoryNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv kategorije je obavezan..
        /// </summary>
        public static string Validation_CategoryNameRequired {
            get {
                return ResourceManager.GetString("Validation_CategoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv kluba ne može biti duži od 200 karaktera..
        /// </summary>
        public static string Validation_ClubNameMaxLength {
            get {
                return ResourceManager.GetString("Validation_ClubNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv kluba je obavezan..
        /// </summary>
        public static string Validation_ClubNameRequired {
            get {
                return ResourceManager.GetString("Validation_ClubNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbor kluba je obavezan..
        /// </summary>
        public static string Validation_ClubRequired {
            get {
                return ResourceManager.GetString("Validation_ClubRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdite lozinku..
        /// </summary>
        public static string Validation_ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("Validation_ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja ne može biti u budućnosti..
        /// </summary>
        public static string Validation_DateOfBirthInvalidFuture {
            get {
                return ResourceManager.GetString("Validation_DateOfBirthInvalidFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takmičar mora imati najmanje 3 godine..
        /// </summary>
        public static string Validation_DateOfBirthMinAge {
            get {
                return ResourceManager.GetString("Validation_DateOfBirthMinAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja je obavezan..
        /// </summary>
        public static string Validation_DateOfBirthRequired {
            get {
                return ResourceManager.GetString("Validation_DateOfBirthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum završetka mora biti nakon datuma početka..
        /// </summary>
        public static string Validation_EndingDateBeforeBeginning {
            get {
                return ResourceManager.GetString("Validation_EndingDateBeforeBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška u validaciji.
        /// </summary>
        public static string Validation_ErrorCaption {
            get {
                return ResourceManager.GetString("Validation_ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime može imati maksimalno 50 karaktera..
        /// </summary>
        public static string Validation_FirstNameMaxLength {
            get {
                return ResourceManager.GetString("Validation_FirstNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno..
        /// </summary>
        public static string Validation_FirstNameRequired {
            get {
                return ResourceManager.GetString("Validation_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo ispravite greške u formi pre čuvanja..
        /// </summary>
        public static string Validation_FixErrorsBeforeSaving {
            get {
                return ResourceManager.GetString("Validation_FixErrorsBeforeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo ispravite greške u formi..
        /// </summary>
        public static string Validation_FixErrorsInForm {
            get {
                return ResourceManager.GetString("Validation_FixErrorsInForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime može imati maksimalno 100 karaktera..
        /// </summary>
        public static string Validation_LastNameMaxLength {
            get {
                return ResourceManager.GetString("Validation_LastNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno..
        /// </summary>
        public static string Validation_LastNameRequired {
            get {
                return ResourceManager.GetString("Validation_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija je obavezna..
        /// </summary>
        public static string Validation_LocationRequired {
            get {
                return ResourceManager.GetString("Validation_LocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka može imati maksimalno 100 karaktera..
        /// </summary>
        public static string Validation_PasswordMaxLength {
            get {
                return ResourceManager.GetString("Validation_PasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora imati najmanje 6 karaktera..
        /// </summary>
        public static string Validation_PasswordMinLength {
            get {
                return ResourceManager.GetString("Validation_PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je obavezna..
        /// </summary>
        public static string Validation_PasswordRequired {
            get {
                return ResourceManager.GetString("Validation_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinke se ne poklapaju..
        /// </summary>
        public static string Validation_PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("Validation_PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plasman mora biti validan broj ili ostati prazan..
        /// </summary>
        public static string Validation_PlacementMustBeANumberOrEmpty {
            get {
                return ResourceManager.GetString("Validation_PlacementMustBeANumberOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plasman mora biti pozitivan broj ukoliko je unesen..
        /// </summary>
        public static string Validation_PlacementMustBePositive {
            get {
                return ResourceManager.GetString("Validation_PlacementMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plasman mora biti pozitivan ceo broj ili ostati prazan..
        /// </summary>
        public static string Validation_PlacementPositiveIntegerOrEmpty {
            get {
                return ResourceManager.GetString("Validation_PlacementPositiveIntegerOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv može imati maksimalno 500 karaktera..
        /// </summary>
        public static string Validation_TournamentNameMaxLength {
            get {
                return ResourceManager.GetString("Validation_TournamentNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv takmičenja je obavezan..
        /// </summary>
        public static string Validation_TournamentNameRequired {
            get {
                return ResourceManager.GetString("Validation_TournamentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime može imati maksimalno 50 karaktera..
        /// </summary>
        public static string Validation_UsernameMaxLength {
            get {
                return ResourceManager.GetString("Validation_UsernameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime mora imati najmanje 3 karaktera..
        /// </summary>
        public static string Validation_UsernameMinLength {
            get {
                return ResourceManager.GetString("Validation_UsernameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je obavezno..
        /// </summary>
        public static string Validation_UsernameRequired {
            get {
                return ResourceManager.GetString("Validation_UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje.
        /// </summary>
        public static string Warning_Generic_Caption {
            get {
                return ResourceManager.GetString("Warning_Generic_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo odaberite takmičara..
        /// </summary>
        public static string Warning_NoCompetitorSelected {
            get {
                return ResourceManager.GetString("Warning_NoCompetitorSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli, {0}.
        /// </summary>
        public static string WelcomeUser {
            get {
                return ResourceManager.GetString("WelcomeUser", resourceCulture);
            }
        }
    }
}
